language: java
env:
  - PLAY_VERSION=2.0.4 MONGODB_URI=mongodb://127.0.0.1/test
services:
  - mongodb
before_script: 
  - wget http://download.playframework.org/releases/play-${PLAY_VERSION}.zip
  - unzip -q play-${PLAY_VERSION}.zip 
  - mongo conf/mongodb/indexes.js
script: play-${PLAY_VERSION}/play test
